name: Build and Notify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '12.x'

      - name: Build with Maven
        run: mvn clean install

      - name: Notify on Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: -1002121798245
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Сборка ${{ job.status }}
            Коммит: ${{ github.sha }}
            Автор: ${{ github.actor }} Аннотации
