    - name: Notify on Telegram
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: @an_grecha
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Build ${{ job.status }}
          Commit: ${{ github.sha }}
          Actor: ${{ github.actor }}
